### ISSUE TITLE
Make joining players' games easier

### ISSUE THREAD

**Issue by KekkyShmekky** [fluffy-servers/gmod-discord-rpc#12]
Hey, so I'm wondering how to get the Gmod RPC to display the button to join people's games easier.

**Comment by rafraser** [comment]
I've looked into this and it's a pretty tricky problem to solve. If you have any ideas, feel free to open a PR.

Main difficulties:
- Launching the game from the Discord button is a pain. The SDK usually links to a Steam ID, but I don't think we can do that since it's not officially our game. We can probably do some command line hackery to get by.

- Connecting to the server once launched. I don't think we can do this directly from C++, so we'll need to get some Lua script working in the menu state which I think is quite challenging.

I'll take another look into it at some point, but I'm not optimistic that it's doable.

**Comment by Kesefon** [comment]
How about using a custom button with a "steam://connect/\<ip\>" url? 
I think Discord introduced custom buttons after deprecating the rpc lib we're using, so we would need to use a modified version (something like https://github.com/Sardonyx78/discord-rpc/commit/8bcb1d63bb4904ff1a7dcbd685f15843e33498c6 ). 
But this should be a simple change.

I can try to implement this later.

**Comment by rafraser** [comment]
I'd like to switch to the official Discord Game SDK, but I'm not sure how to handle the licence side of it

**Comment by KekkyShmekky** [comment]
> How about using a custom button with a "steam://connect/<ip>" url? I think Discord introduced custom buttons after deprecating the rpc lib we're using, so we would need to use a modified version (something like [Sardonyx78/discord-rpc@8bcb1d6](https://github.com/Sardonyx78/discord-rpc/commit/8bcb1d63bb4904ff1a7dcbd685f15843e33498c6) ). But this should be a simple change.
> 
> I can try to implement this later.

I actually tried doing that by changing the text that displays on the player's profile, but it didn't turn into a blue clickable hyperlink.

**Comment by cborac** [comment]
@Kesefon I actually created the fork you sent to implement buttons for this library lol, what a coincidence

**Comment by rafraser** [comment]
A special thankyou to @cborac for their fork of the Discord RPC library & a PR adding buttons to this library!

I'll publish a new Github release later today for easy downloads of the module, but for anyone that's super keen you should be able to get them from [Github Actions here](https://github.com/fluffy-servers/gmod-discord-rpc/actions/runs/6154198318)

**Comment by rafraser** [comment]
Released: https://github.com/fluffy-servers/gmod-discord-rpc/releases/tag/1.2 🎊
